import "./globals.css";
import { Inter } from "next/font/google";
import Providers from "./providers";
import Header from "@/components/Header";
import Modals from "@/components/Modals/Modals";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`debug-screens bg-slate-100 text-zinc-700 h-screen ${inter.className}`}
      >
        <Providers>
          <Modals />
          <div className="container h-full mx-auto xl:px-20 mx-w-6xl">
            <Header />
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
