import "./globals.css";
import { Inter } from "next/font/google";
import Providers from "./providers";
import SideBar from "@/components/sideBar/SideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`debug-screens bg-slate-100 text-zinc-700 h-screen overflow-hidden ${inter.className}`}
      >
        <Providers>
          <div className="flex w-full h-screen mx-auto">
            <SideBar />
            <div className="w-[70%] bg-slate-500">{children}</div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
