import "./globals.css";
import { Inter } from "next/font/google";
import Providers from "./providers";
import SideBar from "@/components/sideBar/SideBar";
import { useRouter } from "next/navigation";
import Header from "@/components/header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`debug-screens bg-slate-100 mx-36 h-screen overflow-hidden ${inter.className}`}
      >
        <Providers>
          <div className="flex flex-col w-full h-screen mx-auto">
            {/* <SideBar /> */}
            <Header />
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
